openapi: 3.0.3
info:
  title: Customer Service API
  description: API para la gestión de clientes bancarios
  version: 1.0.0
servers:
  - url: http://localhost:8585/api/v1
    description: Local development server
paths:
  /customers:
    post:
      tags:
        - Customer
      summary: Create a new customer
      operationId: createCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerRequest'
      responses:
        '201':
          description: Customer created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
        '400':
          description: Invalid request
    get:
      tags:
        - Customer
      summary: Get all customers
      operationId: getAllCustomers
      responses:
        '200':
          description: List of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerResponse'
  /customers/{id}:
    get:
      tags:
        - Customer
      summary: Get customer by ID
      operationId: getCustomerById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Customer found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
        '404':
          description: Customer not found
    put:
      tags:
        - Customer
      summary: Update customer
      operationId: updateCustomer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerRequest'
      responses:
        '200':
          description: Customer updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
        '404':
          description: Customer not found
    delete:
      tags:
        - Customer
      summary: Delete customer
      operationId: deleteCustomer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Customer deleted successfully
        '404':
          description: Customer not found
        '409':
          description: Cannot delete customer with active products
components:
  schemas:
    CustomerRequest:
      type: object
      required:
        - customerType
        - name
        - documentNumber
      properties:
        customerType:
          type: string
          enum: [PERSONAL, BUSINESS]
        name:
          type: string
        documentNumber:
          type: string
        email:
          type: string
        phone:
          type: string
        address:
          type: string
    CustomerResponse:
      type: object
      properties:
        id:
          type: string
        customerType:
          type: string
          enum: [PERSONAL, BUSINESS]
        name:
          type: string
        documentNumber:
          type: string
        email:
          type: string
        phone:
          type: string
        address:
          type: string

